force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Desired_Rent__c.field-meta.xml
<CustomField>
    <fullName>Desired_Rent__c</fullName>
    <label>Desired Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/homePage.cls
public class homePage {
	@AuraEnabled
    public static List<Property__c> top() {
        return [SELECT Desired_Rent__c, Picture__c, Name FROM Property__c ORDER BY Desired_Rent__c DESC NULLS LAST LIMIT 1];
    }
    
    @AuraEnabled
    public static List<Property__c> bot() {
        return [SELECT Desired_Rent__c, Picture__c, Name FROM Property__c ORDER BY Desired_Rent__c ASC NULLS LAST LIMIT 1];
    }
}