force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <description>Approved maintenance tasks requested by tenant or property owner.</description>
    <label>Maintenance Request</label>
    <nameField>
        <label>Maintenance Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Job_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Job_Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the job been awarded to a vendor and a service date scheduled?</description>
    <label>Job Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Maintenance_Type__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Type__c</fullName>
    <description>General type of maintenance required (HVAC, roofing, etc)</description>
    <label>Maintenance Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Electrical Work</fullName>
            </value>
            <value>
                <fullName>Exterior Work</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Paint</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Preferred_Date_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Service__c</fullName>
    <label>Preferred Date of Service</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vendor_Quote__c/Vendor_Quote__c.object-meta.xml
<CustomObject>
    <label>Vendor Quote</label>
    <nameField>
        <label>Vendor Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Quote__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Hourly rate quoted by vendor for this job.</description>
    <label>Hourly Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vendor_Quote__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Maintenance_Request__c</referenceTo>
    <relationshipLabel>Vendor Quotes</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MNMaintenanceRequestController.cls
public class MNMaintenanceRequestController {
    public Date PrefDateStart {get;set;}
    public Date PrefDateEnd {get;set;}    
    public List <Maintenance_Request__c> mRList {get;set;}
    public List <Maintenance_Request__c> vQList {get;set;}
    Boolean isMatch = true;
    public MNMaintenanceRequestController() {
        mRList = [SELECT Name, Maintenance_Type__c, Preferred_Date_of_Service__c, Job_Scheduled__c, (SELECT Name, Hourly_Rate__c FROM Vendor_Quotes__r) FROM Maintenance_Request__c];
    }
    
    public void SearchByDateRange() {

        mRList = [SELECT Name, Maintenance_Type__c, Preferred_Date_of_Service__c, Job_Scheduled__c, (SELECT Name, Hourly_Rate__c FROM Vendor_Quotes__r) FROM Maintenance_Request__c 
                  WHERE Preferred_Date_of_Service__c >= :PrefDateStart AND Preferred_Date_of_Service__c <= :PrefDateEnd];

    }
    
    public void SearchByJobsNotScheduled(){
        mRList = [SELECT Name, Maintenance_Type__c, Preferred_Date_of_Service__c, Job_Scheduled__c, (SELECT Name, Hourly_Rate__c FROM Vendor_Quotes__r) FROM Maintenance_Request__c 
                  WHERE Job_Scheduled__c = false]; 
    }
    public void SearchByJobsScheduled(){
        mRList = [SELECT Name, Maintenance_Type__c, Preferred_Date_of_Service__c, Job_Scheduled__c, (SELECT Name, Hourly_Rate__c FROM Vendor_Quotes__r) FROM Maintenance_Request__c 
                  WHERE Job_Scheduled__c = true]; 
    }
    public void ResetSearch(){
        mRList = [SELECT Name, Maintenance_Type__c, Preferred_Date_of_Service__c, Job_Scheduled__c, (SELECT Name, Hourly_Rate__c FROM Vendor_Quotes__r) FROM Maintenance_Request__c];
    }
}