force-app/main/default/objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <label>Lease Agreement</label>
    <nameField>
        <label>Lease Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Agreement__c/fields/Monthly_Rent_Due__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent_Due__c</fullName>
    <label>Monthly Rent Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Signed_By_Tenant__c.field-meta.xml
<CustomField>
    <fullName>Signed_By_Tenant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the lease agreement been read and signed by the prospective tenant?</description>
    <label>Signed By Tenant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/fields/Lease_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Lease_Agreement__c</fullName>
    <label>Lease Agreement</label>
    <referenceTo>Lease_Agreement__c</referenceTo>
    <relationshipLabel>Tenants</relationshipLabel>
    <relationshipName>Tenants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tenant__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Tenants</relationshipLabel>
    <relationshipName>Tenants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TenantControllerTest.cls
/*
*Name: TenantControllerTest.apxc
*Author: Julia Weakley
*DateCreated: 9/27/2021
*DateModified: 9/30/2021
*Description: 
*	Tests for 
*	Tests cover 
*/
@isTest
public class TenantControllerTest {
    
    
    @isTest static void Test1() {
        // Perform test
        Test.startTest();
        Tenant__c t = TenantController.getTenantInfo();
        Test.stopTest();
        // Verify
        System.assertEquals(null, t);        
    }
    
    @isTest static void Test2() {
        // Perform test
        Test.startTest();
        Lease_Agreement__c tList = TenantController.getLeaseAgreementInfo();
        Test.stopTest();
        // Verify
        System.assertEquals(null, tList);    
    }
    @isTest static void Test3() {
        Lease_Agreement__c temp = new Lease_Agreement__c(); 
        temp.Name = 'Test';
        temp.Monthly_Rent_Due__c = 200; 
        
        temp.Security_Deposit__c = 1000;
        temp.Signed_By_Tenant__c = false; 
        temp.Start_Date__c = System.today();
        temp.End_Date__c = System.today() +100 ;
       
       
        	insert temp;
        	
         
     	
        Lease_Agreement__c tList = TenantController.getLeaseAgreementInfo();
              // Verify
        System.assertEquals(null, tList);  

    }
     @isTest static void Test4() {
        // Perform test
        Test.startTest();
        Property__c prop = TenantController.getPropInfo();
        Test.stopTest();
        // Verify
        System.assertEquals(null, prop);    
    }
}