force-app/main/default/objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <label>Lease Agreement</label>
    <nameField>
        <label>Lease Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Agreement__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Approved</fullName>
                <default>true</default>
                <label>Not Approved</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Monthly_Rent_Due__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent_Due__c</fullName>
    <label>Monthly Rent Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <description>Approved maintenance tasks requested by tenant or property owner.</description>
    <label>Maintenance Request</label>
    <nameField>
        <label>Maintenance Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Job_Completed__c.field-meta.xml
<CustomField>
    <fullName>Job_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the job been completed by the assigned vendor?</description>
    <label>Job Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Quote__c/Vendor_Quote__c.object-meta.xml
<CustomObject>
    <label>Vendor Quote</label>
    <nameField>
        <label>Vendor Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Quote__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <description>Hourly rate quoted by vendor for this job.</description>
    <label>Hourly Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vendor_Quote__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <description>Hours quoted by the vendor for this job.</description>
    <label>Hours</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Quote__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Maintenance_Request__c</referenceTo>
    <relationshipLabel>Vendor Quotes</relationshipLabel>
    <relationshipName>Vendor_Quotes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IncomeExpenseAuraController.cls
public class IncomeExpenseAuraController {
    @AuraEnabled
    public static List<Property__c> getProperties(){
        try {
            return [SELECT Id, Name, Address__c, City__c, State__c, Zip_Code__c FROM Property__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Lease_Agreement__c> getLeaseAgreements(String propertyId){
        try {
            String query = 'SELECT Name, Security_Deposit__c, Monthly_Rent_Due__c, Start_Date__c, End_Date__c FROM Lease_Agreement__c WHERE Approval_Status__c = \'Approved\'';
            if (propertyId != null && !propertyId.equals(''))
                query += ' AND Property__c = \'' + propertyId + '\'';
            return Database.query(query);
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Vendor_Quote__c> getQuotes(String propertyId){
        try {
            String query = 'SELECT Name, Hourly_Rate__c, Hours__c FROM Vendor_Quote__c WHERE Maintenance_Request__r.Job_Completed__c = TRUE';
            if (propertyId != null && !propertyId.equals(''))
                query += ' AND Maintenance_Request__r.Property__c = \'' + propertyId + '\'';
            return Database.query(query);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}