force-app/main/default/objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <label>Lease Agreement</label>
    <nameField>
        <label>Lease Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Agreement__c/fields/Monthly_Rent_Due__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent_Due__c</fullName>
    <label>Monthly Rent Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/fields/Lease_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Lease_Agreement__c</fullName>
    <label>Lease Agreement</label>
    <referenceTo>Lease_Agreement__c</referenceTo>
    <relationshipLabel>Tenants</relationshipLabel>
    <relationshipName>Tenants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tenant__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Tenants</relationshipLabel>
    <relationshipName>Tenants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tenant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tenants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TenantController.cls
/*
*Name: TenantController.apxc
*Author: Julia Weakley
*DateCreated: 9/26/2021
*DateModified: 10/5/2021
*Description: 
*	Tests for 
*	Tests cover 
*/



public class TenantController {

    
   // retrieve tenant associated with user 
   // written by Canbin Mei
    @AuraEnabled
    public static Tenant__c getTenantInfo() 
    {
        
        try {
            // Query for the fields from Tenant__c where the owner's id = current user's id.
            List<Tenant__c> tList = [SELECT Name, Email__c, Primary_Phone__c,  Id 
                                     FROM Tenant__c 
                                     WHERE User__c = :UserInfo.getUserId()];
            
         	// retun tenant found  
            return tList[0];
        } // end of try
        catch(Exception e) 
        {
            System.debug('There is no result return from the query.');
            return null;
        } // end of catch
        
    } // end of getTenantinfo
    
    // retrieves lease associated with tenant amd user
    // written by Canbin Mei, edited by Julia Weakley
   @AuraEnabled
    public static Lease_Agreement__c getLeaseAgreementInfo() 
    {
        // query for lease associated with tenant attached to current user
        List<Tenant__c> tList = [SELECT id,Lease_Agreement__r.id, Lease_Agreement__r.Name, Lease_Agreement__r.Start_Date__c, Lease_Agreement__r.End_Date__c, Lease_Agreement__r.Monthly_Rent_Due__c
                                 FROM Tenant__c 
                                 WHERE User__c = :UserInfo.getUserId()];
        // if nothing is in list return null
       if(tList.size() ==0)
       {
           return null; 
       } // end of if 
        
        // if there is something in list of tenants grab lease
        Lease_Agreement__c lease = new Lease_Agreement__c(id= tList[0].Lease_Agreement__r.id, Name=  tList[0].Lease_Agreement__r.Name, Start_Date__c=  tList[0].Lease_Agreement__r.Start_Date__c, End_Date__c=  tList[0].Lease_Agreement__r.End_Date__c, Monthly_Rent_Due__c = tList[0].Lease_Agreement__r.Monthly_Rent_Due__c ); 
      
        // return lease
        return lease;   
    } // end of getLeaseAgreementInfo
    
    // retrieves property associated with lease, tenant, and user 
    @AuraEnabled
    public static Property__c getPropInfo() 
    {
        // query for tenant information associated with user
        List<Tenant__c> tList = [SELECT id, Property__r.Id
                                 FROM Tenant__c 
                                 WHERE User__c = :UserInfo.getUserId()];
       // if nothing was found return null
       if(tList.size() == 0)
       {
           return null; 
       } // end of if
        
        // if tenant was found grab associated property
        Property__c np = new Property__c(id= tList[0].Property__r.Id);
        
        // return property found 
        return np; 
    } // end of getPropInfo 
} // end of TenantController