force-app/main/default/objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <label>Lease Agreement</label>
    <nameField>
        <label>Lease Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Agreement__c/fields/Monthly_Rent_Due__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent_Due__c</fullName>
    <label>Monthly Rent Due</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Security_Deposit__c</fullName>
    <label>Security Deposit</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/fields/Lease_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Lease_Agreement__c</fullName>
    <label>Lease Agreement</label>
    <referenceTo>Lease_Agreement__c</referenceTo>
    <relationshipLabel>Tenants</relationshipLabel>
    <relationshipName>Tenants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tenant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tenants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CmTenantController.cls
public class CmTenantController {
    
    // UserId: 0055f000002S8PMAA0
    public static Tenant__C getTenantInfo() {
        
        try {
            // Query for the fields from Tenant__c where the owner's id = current user's id.
            List<Tenant__c> tList = [SELECT Name, Email__c, Primary_Phone__c, Id 
                                     FROM Tenant__c 
                                     WHERE User__c = :UserInfo.getUserId()];
            return tList[0];
        } catch(Exception e) {
            System.debug('There is no result return from the query.');
            return null;
        }
        
    }
    
    // SELECT Tenant__c.Name, Tenant__c.Lease_Agreement__r.Name FROM Tenant__c WHERE User__c = '0055f000002S8PMAA0'
    public static List<Tenant__c> getLeaseAgreementInfo() {
        List<Tenant__c> tList = [SELECT  
                                 Tenant__c.Lease_Agreement__r.Name, 
                                 Tenant__c.Lease_Agreement__r.Start_Date__c, 
                                 Tenant__c.Lease_Agreement__r.End_Date__c, 
                                 Tenant__c.Lease_Agreement__r.Monthly_Rent_Due__c, 
                                 Tenant__c.Lease_Agreement__r.Security_Deposit__c
                                 FROM Tenant__c 
                                 WHERE User__c = :UserInfo.getUserId()];
        return tList;   
    }
    
}