force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Main office for an area or region.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Electrical Work</fullName>
            </value>
            <value>
                <fullName>Exterior Work</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Paint</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MaintenanceVendorAuraControllerTest.cls
@isTest
private class MaintenanceVendorAuraControllerTest {
    
    @TestSetup
    static void makeData(){
        //Create some branches.
        List<Branch__c> branches = new List<Branch__c>();
        branches.add(new Branch__c(Name = 'Branch1'));
        branches.add(new Branch__c(Name = 'Branch2'));
        branches.add(new Branch__c(Name = 'SomeOffBranch'));

        insert branches;

        //Create some Vendors
        List<Vendor__c> vendors = new List<Vendor__c>();
        vendors.add(new Vendor__c(Name = 'Carpet Cleaners A', Email__c = 'info@carpetcleaners.com', Specialty__c = 'Cleaning', Branch__c = branches[0].Id));
        vendors.add(new Vendor__c(Name = 'Carpet Cleaners B', Email__c = 'info2@carpetcleaners.com', Specialty__c = 'Cleaning', Branch__c = branches[1].Id));
        vendors.add(new Vendor__c(Name = 'Masonry Repairmen', Email__c = 'info@masonry.com', Specialty__c = 'Exterior Work', Branch__c = branches[0].Id));
        vendors.add(new Vendor__c(Name = 'Carpet Builders A', Email__c = 'info@carpetbuilders.com', Specialty__c = 'Flooring', Branch__c = branches[0].Id));
        vendors.add(new Vendor__c(Name = 'Carpet Builders B', Email__c = 'info2@carpetbuilders.com', Specialty__c = 'Flooring', Branch__c = branches[1].Id));
        vendors.add(new Vendor__c(Name = 'Super Mario Bros.', Email__c = 'info@nintendo.com', Specialty__c = 'Plumbing', Branch__c = branches[0].Id));
        vendors.add(new Vendor__c(Name = 'Bob Ross Enterprises', Email__c = 'bob@bobross.com', Specialty__c = 'Painting', Branch__c = branches[2].Id));

        insert vendors;
    }

    @isTest
    static void specialtiesTest() {
        List<String> specialtyList = MaintenanceVendorAuraController.getSpecialties();
        System.assert(specialtyList.contains('Cleaning'));
        System.assert(specialtyList.contains('Electrical Work'));
        System.assert(specialtyList.contains('Exterior Work'));
        System.assert(specialtyList.contains('Flooring'));
        System.assert(specialtyList.contains('HVAC'));
        System.assert(specialtyList.contains('Landscaping'));
        System.assert(specialtyList.contains('Paint'));
        System.assert(specialtyList.contains('Roofing'));
        System.assert(specialtyList.contains('Plumbing'));
        System.assertEquals(9, specialtyList.size());
    }

    @isTest
    static void vendorCountTest() {
        System.assertEquals(7, MaintenanceVendorAuraController.getVendorCount('', ''));
        System.assertEquals(0, MaintenanceVendorAuraController.getVendorCount('Bill', ''));
        System.assertEquals(2, MaintenanceVendorAuraController.getVendorCount('', 'Cleaning'));
        System.assertEquals(5, MaintenanceVendorAuraController.getVendorCount('b', ''));
        System.assertEquals(0, MaintenanceVendorAuraController.getVendorCount('Mario', 'Exterior Work'));
    }

    @isTest
    static void vendorListTest() {
        List<Vendor__c> vendorsWithMa = MaintenanceVendorAuraController.getVendorList('ma', '', '', 0, 0);
        System.assert(vendorsWithMa[0].Specialty__c.equals('Plumbing') || vendorsWIthMa[1].Specialty__c.equals('Plumbing'));

        List<Vendor__c> cleaningVendors = MaintenanceVendorAuraController.getVendorList('', 'Cleaning', 'Name', 0, 0);
        System.assertEquals('Carpet Cleaners B', cleaningVendors[1].Name);

        List<Vendor__c> vendorsSortedByBranch = MaintenanceVendorAuraController.getVendorList('', '', 'Branch__r.Name', 0, 0);
        System.assertEquals('Bob Ross Enterprises', vendorsSortedByBranch[vendorsSortedByBranch.size() - 1].Name);
    }
}