force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Main office for an area or region.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Electrical Work</fullName>
            </value>
            <value>
                <fullName>Exterior Work</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Paint</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MaintenanceVendorController.cls
public class MaintenanceVendorController {
    private String sortOrder2 = 'Name';
    private String specialty = 'Plumbing';
    public String getsortOrder2(){
        return sortOrder2;
    }
    public String getspecialty(){
        return specialty;
    }
 
    Public List<Vendor__c> getVendors(){
        List<Vendor__c> results = Database.query(
        'SELECT Id, Name, Branch__c, Email__c, Primary_phone__c, Specialty__c ' +
        'FROM Vendor__c '+
        'WHERE specialty__c = :specialty ' +
        'ORDER BY ' + sortOrder2 + ' ASC ' +
        'LIMIT 8'
        );
        return results;
    }
    
    public void sortByName(){
        this.sortOrder2 = 'Name';
    }
    
    public void sortByBranch(){
        this.sortOrder2 = 'branch__c';
    }
    
    //This will be for each Specialty
    
    public void viewCleaning(){
        this.specialty = 'Cleaning';
    }
    public void viewElectrical(){
        this.specialty = 'Electrical Work';
    }
    public void viewExterior(){
        this.specialty = 'Exterior Work';
    }
    public void viewFlooring(){
        this.specialty = 'Flooring';
    }
    public void viewHVAC(){
        this.specialty = 'HVAC';
    }
    public void viewLandscaping(){
        this.specialty = 'Landscaping';
    }
    public void viewPaint(){
        this.specialty = 'Paint';
    }
    public void viewPlumbing(){
        this.specialty = 'Plumbing';
    }
    public void viewRoofing(){
        this.specialty = 'Roofing';
    }
    
    
}