force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Main office for an area or region.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>Bedrooms__c</fullName>
    <label>Bedrooms</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Desired_Rent__c.field-meta.xml
<CustomField>
    <fullName>Desired_Rent__c</fullName>
    <label>Desired Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Include_in_Marketing__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this property currently on the market for a tenant?</description>
    <inlineHelpText>Is this property currently on the market for a tenant?</inlineHelpText>
    <label>Include in Marketing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Manager__c.field-meta.xml
<CustomField>
    <fullName>Property_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Manager</label>
    <referenceTo>Property_Manager__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Manager__c/Property_Manager__c.object-meta.xml
<CustomObject>
    <description>Have multiple properties assigned to their management.</description>
    <label>Property Manager</label>
    <nameField>
        <label>Property Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Manager__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Property Managers</relationshipLabel>
    <relationshipName>Property_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketingListController.cls
public class MarketingListController {
    @AuraEnabled
    public static List<Property__c> getProperty(Integer setsize, Integer numBathrooms, Integer numBedrooms, Integer maxRent) {
        String query = 'SELECT Name, Address__c, Zip_Code__c, Property_Manager__r.Name, Property_Manager__r.Email__c, Property_Manager__r.Phone__c, Property_Manager__r.Branch__r.Name, Desired_Rent__c, Picture__c, Bedrooms__c, Bathrooms__c FROM Property__c WHERE Include_in_Marketing__c = True AND Bathrooms__c >= ' + numBathrooms + ' AND Bedrooms__c >= ' + numBedrooms;
        if (maxRent != null && maxRent <= 0)
            query += ' AND Desired_Rent__c <= ' + maxRent;
        query += ' LIMIT 1 OFFSET ' + setsize;
        System.debug(query);
        List<Property__c> displayProp = Database.query(query);
        return displayProp;
    }
}