force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Main office for an area or region.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Street Address</description>
    <label>Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>Bedrooms__c</fullName>
    <label>Bedrooms</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Desired_Rent__c.field-meta.xml
<CustomField>
    <fullName>Desired_Rent__c</fullName>
    <label>Desired Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Include_in_Marketing__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this property currently on the market for a tenant?</description>
    <inlineHelpText>Is this property currently on the market for a tenant?</inlineHelpText>
    <label>Include in Marketing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Manager__c.field-meta.xml
<CustomField>
    <fullName>Property_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Manager</label>
    <referenceTo>Property_Manager__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Manager__c/Property_Manager__c.object-meta.xml
<CustomObject>
    <description>Have multiple properties assigned to their management.</description>
    <label>Property Manager</label>
    <nameField>
        <label>Property Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Manager__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Property Managers</relationshipLabel>
    <relationshipName>Property_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LHMarketingListController.cls
public class LHMarketingListController {
    public integer totalRecs{get; set;}
    public integer OffsetSize=0;
    public integer LimitSize{get; set;} {LimitSize = 1;}
    public decimal numberBathrooms{get; set;} //{numberBathrooms = 10;}
    public integer numberBedrooms{get; set;} //{numberBedrooms = 10;}
    public integer rentFilter{get; set;} {rentFilter = 10000;}
    
    public LHMarketingListController(){
        totalRecs = [SELECT Count() FROM Property__c WHERE Include_in_Marketing__c = True];
    }
    
    public List<Property__c> getPropertyList(){
        numberBathrooms = Integer.valueOf(numberBathrooms);
        numberBedrooms = Integer.valueOf(numberBedrooms);
        rentFilter = Integer.valueOf(rentFilter);
        List<Property__c> prop = Database.Query('SELECT Name, Address__c, Zip_Code__c, Property_Manager__r.Name, Property_Manager__r.Email__c, Property_Manager__r.Phone__c, Property_Manager__r.Branch__r.Name, Desired_Rent__c, Picture__c, Bedrooms__c, Bathrooms__c ' +
                                            	'FROM Property__c WHERE Include_in_Marketing__c=True AND Bedrooms__c >= :numberBedrooms AND Bathrooms__c >= :numberBathrooms AND Desired_Rent__c <= :rentFilter ' +
                                                'ORDER BY Desired_Rent__c DESC LIMIT 1 OFFSET :OffsetSize');
        List<Property__c> matchProp = Database.Query('SELECT Name, Address__c, Zip_Code__c, Property_Manager__c, Desired_Rent__c, Picture__c, Bedrooms__c, Bathrooms__c ' + 
                                            		'FROM Property__c WHERE Include_in_Marketing__c=True AND Bedrooms__c >= :numberBedrooms AND Bathrooms__c >= :numberBathrooms AND Desired_Rent__c <= :rentFilter ');
        totalRecs = matchProp.Size();
        return prop;
    }
    
    public void previous() {
        OffsetSize = OffsetSize - 1;
    }
    
    public void next() {
        OffsetSize = OffsetSize + 1;
    }
    
    public boolean getdisabledPrev() {
		 if(OffsetSize>0)
             return false;
         else 
             return true;
    }
    
    public boolean getdisabledNext() {
        if(OffsetSize + 1 < totalRecs)
            return false;
        else
            return true;      
    }

}